# version: '3.8'
# services:
#   mssql:
#     image: "mcr.microsoft.com/mssql/server:2022-latest"
#     container_name: "mssql_container"
#     ports:
#       - "1433:1433"
#     environment:
#       SA_PASSWORD: "YourSecurePassword123!"
#       ACCEPT_EULA: "Y"
#     restart: always


version: '3.8'
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "mssql_container"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourSecurePassword123!"
      ACCEPT_EULA: "Y"
    restart: always

  mongo:
    image: "mongo:latest"
    container_name: "mongo_container"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootpassword"
    restart: always
